// DATA for s By Benefit and children components

const PoseBenefitData = [
  // index 0 obj = symptoms
  {
    Symptoms: {
      "Relieves stress/anxiety": [
        "Cat",
        "Dolphin",
        "King Pigeon",
        "Half Boat",
        "Half-Moon",
        "Handstand",
        "Plow",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Lotus",
        "Shoulder Stand",
        "Side Plank",
        "Triangle",
      ],
      "Improves digestion": [
        "Half-Moon",
        "Cat",
        "Dolphin",
        "Half Boat",
        "Half-Moon",
        "Plow",
        "Pyramid",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Triangle",
        "Shoulder Stand",
        "Side Plank",
      ],
      "Improves balance": [
        "Extended Side Angle",
        "Reverse Warrior",
        "Eagle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "Warrior Three",
        "Pyramid",
        "Tree",
      ],
      "Improve/ Work toward Splits": [
        "Low Lunge",
        "Pyramid",
        "Pigeon",
        "Butterfly",
        "Seated Forward Bend",
        "Extended Hand to Toe",
        "King Pigeon",
        "Standing Forward Bend",
      ],
      "Mild depression": [
        "Dolphin",
        "Wild Thing",
        "Handstand",
        "Plow",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Side Plank",
        "Sphinx",
        "Standing Forward Bend",
        "Upward-Facing Dog",
        "Wheel",
      ],
      "Helps relieve the symptoms of menopause": [
        "Dolphin",
        "Half-Moon",
        "Plow",
        "Shoulder Stand",
        "Side Plank",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Triangle",
      ],
      "Reduces fatigue": [
        "Lotus",
        "Chair",
        "Dolphin",
        "Wild Thing",
        "Plow",
        "Side Plank",
        "Upward-Facing Dog",
        "Pyramid",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Standing Forward Bend",
      ],
      Posture: [
        "Bow",
        "Bridge",
        "Camel",
        "Cat",
        "Chair",
        "Dolphin",
        "Extended Side Angle",
        "Forward Bend with Shoulder Opener",
        "Garland Pose",
        "Plank",
        "King Pigeon",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Sphinx",
        "Standing Forward Bend",
        "Triangle",
        "Upward-Facing Dog",
        "Wheel",
        "Shoulder Stand",
        "Side Plank",
      ],
      "Menstrual Pain": [
        "Dolphin",
        "Butterfly",

        "Child's Pose",
        "Seated Forward Bend",
        "Pigeon",
      ],
      Backache: [
        "Reverse Warrior",
        "Cat",
        "Dolphin",
        "Garland Pose",
        "Child's Pose",
        "Cow",
        "Downward-Facing Dog",
        "Bridge",
        "Plank",
      ],
      Headache: [
        "Dolphin",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Child's Pose",
        "Cat",
        "Cow",
        "Downward-Facing Dog",
        "Bridge",
        "Corpse",
      ],
      Insomnia: [
        "Dolphin",
        "Forward Bend with Shoulder Opener",
        "Shoulder Stand",
        "Plow",
        "Bridge",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Child's Pose",
        "Corpse",
        "Downward-Facing Dog",
        "Corpse",
      ],
      "Flat Feet": [
        "Chair",
        "Dolphin",
        "Reverse Warrior",
        "Side Plank",
        "Triangle",
        "Warrior Two",
        "Downward-Facing Dog",
        "Tree",
      ],
      Sciatica: [
        "Cat",
        "Cow",
        "Child's Pose",
        "Extended Hand to Toe",
        "Pigeon",
        "King Pigeon",
        "Dolphin",
        "Downward-Facing Dog",
        "Reverse Warrior",
        "Side Plank",
        "Triangle",
        "Warrior Two",
        "Upward-Facing Dog",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Wheel",
      ],
    },
  },

  // index 1 obj = stretch
  {
    Stretches: {
      "Stretches the abdomen": [
        "Extended Side Angle",
        "Half-Moon",
        "Reverse Warrior",
        "Cat",
        "Wild Thing",
        "King Pigeon",
        "Butterfly",
        "Child's Pose",
        "Cow",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Forward Bend with Shoulder Opener",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Sphinx",
        "Upward-Facing Dog",
        "Camel",
        "Half Lord of the Fishes",
        "Bow",
      ],
      "Stretches the entire front of body": [
        "Extended Side Angle",
        "Bow",

        "Low Lunge",
        "Crescent Moon",

        "Bridge",
        "Upward-Facing Dog",
        "Camel",
        "Wild Thing",
        "Standing Forward Bend",
        "King Pigeon",
        "Downward-Facing Dog",
      ],
      arms: [
        "Bow",
        "Camel",
        "Cat",
        "Cow",
        "Dolphin",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Garland Pose",
        "Half-Moon",
        "Handstand",
        "King Pigeon",
        "Plank",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Side Plank",
        "Sphinx",
        "Wheel",
        "Upward-Facing Dog",
        "Downward-Facing Dog",
        "Wild Thing",
        "Boat",
        "Crow",
        "Eagle",
        "Forearm Stand",

        "Plank",
      ],
      "Ankles, calves, or feet": [
        "Extended Side Angle",
        "Half-Moon",
        "Lotus",
        "Low Lunge",
        "Warrior One",
        "Warrior Two",
        "Bow",
        "Extended Hand to Toe",
        "Seated Forward Bend",
        "Triangle",
        "Standing Forward Bend",
        "Reverse Warrior",
        "Chair",
        "Dolphin",
        "Garland Pose",
        "Upward-Facing Dog",
        "Downward-Facing Dog",
      ],
      Hamstrings: [
        "Boat",
        "Bow",
        "Bridge",
        "Butterfly",
        "Camel",
        "Cat",
        "Chair",
        "Child's Pose",
        "Corpse",
        "Crescent Lunge",
        "Crescent Moon",
        "Dolphin",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forward Bend with Shoulder Opener",
        "Garland Pose",
        "Half Boat",
        "Half-Moon",
        "Handstand",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Side Splits",
        "Splits",
        "Standing Forward Bend",
        "Triangle",
        "Upward-Facing Dog",
        "Wheel",
      ],
      Quads: [
        "Bow",
        "Camel",
        "Cat",
        "Chair",
        "Child's Pose",
        "Crescent Lunge",
        "Crescent Moon",
        "Dolphin",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forearm Stand",
        "Garland Pose",
        "Half Boat",
        "Half-Moon",
        "King Pigeon",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Side Splits",
        "Sphinx",
        "Splits",
        "Standing Forward Bend",
        "Tree",
        "Upward-Facing Dog",
        "Warrior One",
        "Warrior Three",
        "Warrior Two",
        "Wheel",
      ],
      back: [
        "Half Lord of the Fishes",
        "Half-Moon",
        "Low Lunge",
        "Wild Thing",
        "Garland Pose",
        "Boat",
        "Bow",
        "Camel",
        "Cat",
        "Cow",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Plow",
        "Wheel",
      ],
      "neck and shoulders": [
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Low Lunge",
        "Reverse Warrior",
        "Chair",
        "Dolphin",
        "Wild Thing",
        "King Pigeon",
        "Cat",
        "Cow",
      ],
      Chest: [
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Reverse Warrior",
        "Chair",
        "Wild Thing",
        "King Pigeon",
        "Boat",
        "Bow",
        "Camel",
        "Child's Pose",
        "Standing Forward Bend",
      ],
      Core: [
        "Extended Side Angle",
        "Half-Moon",
        "Half Lord of the Fishes",
        "Reverse Warrior",
        "Wild Thing",
        "Boat",
        "Bow",
        "Bridge",
        "Cat",
        "Cow",
        "Crow",
        "Eagle",
        "Forearm Stand",
        "Handstand",
        "Plank",
        "Plow",
        "Side Plank",
        "Shoulder Stand",
        "Wheel",
      ],
      Hips: [
        "Extended Side Angle",
        "Half-Moon",
        "Lotus",
        "Wild Thing",
        "Splits",
        "Side Splits",
        "Garland Pose",
        "King Pigeon",
        "Butterfly",
        "Bridge",
        "Chair",
        "Crescent Lunge",
        "Crescent Moon",
        "Pigeon",
        "Low Lunge",
        "Standing Forward Bend",
        "Warrior One",
        "Warrior Two",
        "Warrior Three",
      ],
      "Groin and inner thighs": [
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Lotus",
        "Reverse Warrior",
        "Wild Thing",
        "Splits",
        "Side Splits",
        "Garland Pose",
        "Butterfly",
        "Bridge",
        "Camel",
        "Crescent Lunge",
        "Crescent Moon",
        "King Pigeon",
        "Pigeon",
        "Low Lunge",
        "Standing Forward Bend",
        "Warrior One",
        "Warrior Two",
        "Warrior Three",
      ],
      Legs: [
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Lotus",
        "Reverse Warrior",
        "Reverse Warrior",
        "Dolphin",
        "Wild Thing",
        "Side Splits",
        "King Pigeon",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Standing Forward Bend",
      ],
      Neck: [
        "Camel",
        "Cat",
        "Child's Pose",

        "Cow",
        "Dolphin",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Garland Pose",
        "Half Lord of the Fishes",
        "Plow",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Sphinx",
        "Upward-Facing Dog",
        "Wheel",
      ],
      Shoulders: [
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Reverse Warrior",
        "Chair",
        "Dolphin",
        "Wild Thing",
        "King Pigeon",
        "Boat",
        "Bow",
        "Camel",
        "Child's Pose",
        "Standing Forward Bend",
      ],
      Spine: [
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Reverse Warrior",
        "Chair",
        "Dolphin",
        "Wild Thing",
        "Boat",
        "Bow",
        "Camel",
        "Cat",
        "Cow",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Plow",
        "Wheel",
      ],
      "Entire body": [
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Cat",
        "Chair",
        "Child's Pose",
        "Cow",
        "Crescent Lunge",
        "Crescent Moon",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forearm Stand",
        "Garland Pose",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "King Pigeon",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Side Plank",
        "Standing Forward Bend",
        "Tree",
        "Upward-Facing Dog",
        "Warrior One",
        "Warrior Two",
        "Warrior Three",
        "Wheel",
        "Wild Thing",
      ],
      Glutes: [
        "Bridge",
        "Camel",
        "Chair",
        "Crescent Lunge",
        "Crescent Moon",
        "Cow",
        "Dolphin",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Garland Pose",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "King Pigeon",
        "Low Lunge",
        "Pigeon",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Side Splits",
        "Sphinx",
        "Splits",
        "Standing Forward Bend",
        "Triangle",
        "Warrior One",
        "Warrior Two",
        "Warrior Three",
        "Wheel",
      ],
    },
  },

  // index 2 obj = strengthen
  {
    Strengthens: {
      "Strengthens the abdomen": [
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Cat",
        "Chair",
        "Crescent Lunge",
        "Crescent Moon",
        "Crow",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forearm Stand",
        "Garland Pose",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "Low Lunge",
        "Plank",
        "Plow",
        "Pyramid",
        "Seated Forward Bend",
        "Side Plank",
        "Sphinx",
        "Splits",
        "Standing Forward Bend",
        "Upward-Facing Dog",
        "Wheel",
      ],
      Arms: [
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Cat",
        "Crow",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Forearm Stand",
        "Handstand",
        "Plank",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Side Plank",
        "Shoulder Stand",
        "Upward-Facing Dog",
        "Wheel",
      ],

      Back: [
        "Half-Moon",
        "Wild Thing",
        "Boat",
        "Bow",
        "Camel",
        "Cat",

        "Cow",
        "Dolphin",

        "Half Boat",
        "Half Lord of the Fishes",
        "Sphinx",
        "Upward-Facing Dog",
        "Downward-Facing Dog",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Plow",
        "Wheel",
      ],
      "Back, neck, and shoulders": [
        "Warrior Two",
        "Eagle",
        "Forearm Stand",
        "Handstand",
        "Shoulder Stand",
        "Plank",
        "Bridge",

        "Upward-Facing Dog",
        "Dolphin",
        "Wild Thing",
        "Cat",
        "Cow",
      ],
      // STRENGTHEN
      Chest: [
        "Boat",
        "Bow",
        "Camel",
        "Cat",
        "Crescent Moon",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Forearm Stand",
        "Garland Pose",
        "Half Boat",
        "Half-Moon",
        "Handstand",
        "King Pigeon",
        "Pigeon",
        "Plank",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Sphinx",
        "Upward-Facing Dog",
        "Wheel",
        "Wild Thing",
      ],
      Core: [
        "Extended Side Angle",
        "Half-Moon",
        "Reverse Warrior",
        "Side Splits",
        "Garland Pose",
        "Boat",
        "Bow",
        "Bridge",
        "Cat",
        "Cow",
        "Crow",
        "Eagle",
        "Forearm Stand",
        "Handstand",
        "Plank",
        "Plow",
        "Side Plank",
        "Shoulder Stand",
        "Wheel",
      ],

      Glutes: [
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Chair",
        "Crescent Lunge",
        "Crescent Moon",
        "Dolphin",
        "Eagle",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forearm Stand",
        "Garland Pose",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "King Pigeon",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Side Plank",
        "Side Splits",
        "Sphinx",
        "Standing Forward Bend",
        "Tree",
        "Triangle",
        "Upward-Facing Dog",
        "Warrior One",
        "Warrior Three",
        "Warrior Two",
        "Wheel",
        "Wild Thing",
      ],
      Hips: [
        "Extended Side Angle",
        "Splits",
        "Side Splits",
        "Butterfly",
        "Bridge",
        "Chair",
        "Crescent Lunge",
        "Crescent Moon",
        "Pigeon",
        "Low Lunge",
        "Standing Forward Bend",
        "Warrior One",
        "Warrior Two",
        "Warrior Three",
      ],
      "Hips, groin, and inner thighs": [
        "Extended Side Angle",
        "Half-Moon",
        "Splits",
        "Side Splits",
        "Butterfly",
        "Bridge",
        "Camel",
        "Crescent Lunge",
        "Crescent Moon",
        "Pigeon",
        "Low Lunge",
        "Standing Forward Bend",
        "Warrior One",
        "Warrior Two",
        "Warrior Three",
      ],

      Legs: [
        "Crescent Lunge",
        "Crescent Moon",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Garland Pose",

        "Half-Moon",
        "Low Lunge",
        "Pyramid",

        "Reverse Warrior",
        "Seated Forward Bend",
        "Side Splits",
        "Standing Forward Bend",
        "Tree",
        "Triangle",
        "Warrior One",
        "Warrior Three",
        "Warrior Two",
        "Chair",
        "Dolphin",
        "Downward-Facing Dog",
      ],
      Neck: [
        "Dolphin",
        "Eagle",
        "Forearm Stand",
        "Extended Side Angle",
        "Half Lord of the Fishes",
        "Plank",
        "Reverse Warrior",
        "Sphix",
        "Upward-Facing Dog",
        "Wheel",
        "Bow",
        "Bridge",
        "Handstand",
        "Plow",
        "Camel",
        "Shoulder Stand",
        "Cat",
        "Cow",
      ],
      Shoulders: [
        "Bridge",
        "Camel",
        "Cow",
        "Crescent Lunge",
        "Crescent Moon",
        "Crow",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forearm Stand",
        "Forward Bend with Shoulder Opener",
        "Garland Pose",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Side Plank",
        "Sphinx",
        "Standing Forward Bend",
        "Upward-Facing Dog",
        "Wheel",
      ],
      Spine: [
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Cat",
        "Chair",

        "Cow",
        "Crescent Lunge",
        "Crescent Moon",
        "Crow",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Extended Side Angle",

        "Forearm Stand",
        "Garland Pose",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Sphinx",
        "Splits",
        "Standing Forward Bend",
        "Upward-Facing Dog",
        "Wide-Legged Forward Bend",
        "Wild Thing",
        "Wheel",
      ],
      "Entire body": [
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Chair",

        "Corpse",
        "Cow",
        "Crescent Lunge",
        "Crescent Moon",
        "Crow",
        "Dolphin",
        "Downward-Facing Dog",
        "Eagle",
        "Extended Hand to Toe",
        "Extended Side Angle",
        "Forearm Stand",
        "Forward Bend with Shoulder Opener",
        "Garland Pose",
        "Half Boat",
        "Half Lord of the Fishes",
        "Half-Moon",
        "Handstand",
        "King Pigeon",
        "Lotus",
        "Low Lunge",
        "Pigeon",
        "Plank",
        "Plow",
        "Pyramid",
        "Reverse Warrior",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Side Plank",
        "Side Splits",
        "Sphinx",
        "Splits",
        "Tree",
        "Triangle",
        "Upward-Facing Dog",
        "Warrior One",
        "Warrior Three",
        "Warrior Two",
        "Wheel",
        "Wild Thing",
      ],
    },
  },

  // index 3 obj = stimulate
  {
    Stimulates: {
      "Stimulates abdominal organs": [
        "Extended Side Angle",
        "Half-Moon",
        "Reverse Warrior",
        "Chair",
        "Splits",
        "Side Splits",
        "King Pigeon",
        "Boat",
        "Bow",
        "Bridge",
        "Camel",
        "Cat",
        "Cow",
        "Plow",
        "Wheel",
        "Chair",
        "Shoulder Stand",
      ],
      "Stimulates lungs": [
        "Reverse Warrior",
        "Bow",
        "Butterfly",
        "Bridge",

        "Upward-Facing Dog",
        "Pigeon",
        "Child's Pose",
      ],
      "Stimulates thyroids": [
        "Shoulder Stand",
        "Plow",
        "Bridge",
        "Camel",
        "Wheel",
        "Boat",
        "Half Boat",
      ],
      "Stimulates kidneys and adrenal glands": [
        "Bridge",
        "Camel",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Triangle",
        "Wheel",
        "Plow",
        "Upward-Facing Dog",
        "Shoulder Stand",
        "Half Boat",
      ],
      "Stimulates liver and spleen": [
        "Seated Forward Bend",
        "Triangle",
        "Bow",
        "Camel",
        "Chair",
        "Plow",
        "Upward-Facing Dog",
        "Wheel",
        "Shoulder Stand",
        "Half Boat",
      ],
      "Stimulates the brain and improves memory, focus, or concerntration": [
        "Extended Side Angle",
        "Child's Pose",
        "Corpse",
        "Downward-Facing Dog",

        "Shoulder Stand",
        "Seated Forward Bend",
      ],
      "Stimulates the nervous system": [
        "Child's Pose",
        "Corpse",
        "Downward-Facing Dog",

        "Shoulder Stand",
        "Seated Forward Bend",
      ],
      "Stimulates digestion": [
        "Extended Side Angle",
        "Garland Pose",
        "Half Boat",
        "Half-Moon",
        "Plow",
        "Pyramid",
        "Seated Forward Bend",
        "Standing Forward Bend",
        "Triangle",
        "Shoulder Stand",
        "Side Plank",
      ],
      "Stimulates reproductive organs": [
        "Wheel",
        "Warrior Two",
        "Triangle",
        "Shoulder Stand",
        "Seated Forward Bend",
        "Reverse Warrior",
        "Plow",
        "Butterfly",
        "Camel",

        "Cow",
        "Lotus",
        "Pigeon",
        "Seated Forward Bend",
        "Shoulder Stand",
        "Wheel",
      ],
      "Stimulates the thyroid gland": [
        "Shoulder Stand",
        "Bridge",
        "Camel",

        "Plow",
        "Wheel",
      ],
      "Stimulates the pancreas": [
        "Bow",
        "Camel",
        "Child's Pose",

        "Cow",

        "Plow",
        "Seated Forward Bend",
        "Upward-Facing Dog",
        "Wheel",
      ],
    },
  },
];
export default PoseBenefitData;
